<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="ShareefDell" failures="6" tests="20" name="NCTest" time="33.174" errors="0" timestamp="07 Jan 2024 11:31:41 GMT">
  <testcase classname="testNGExamples.TestExample7" name="testMethod" time="0.188">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNGExamples.TestExample7.testMethod() didn&amp;apos;t finish within the time-out 100">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNGExamples.TestExample7.testMethod() didn't finish within the time-out 100
at java.base@17.0.9/java.io.FileOutputStream.writeBytes(Native Method)
at java.base@17.0.9/java.io.FileOutputStream.write(FileOutputStream.java:349)
at java.base@17.0.9/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
at java.base@17.0.9/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
at java.base@17.0.9/java.io.PrintStream.write(PrintStream.java:570)
at java.base@17.0.9/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
at java.base@17.0.9/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
at java.base@17.0.9/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:111)
at java.base@17.0.9/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:178)
at java.base@17.0.9/java.io.PrintStream.writeln(PrintStream.java:723)
at java.base@17.0.9/java.io.PrintStream.println(PrintStream.java:1028)
at app//testNGExamples.TestExample7.testMethod(TestExample7.java:9)
at java.base@17.0.9/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base@17.0.9/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.9/java.lang.Thread.run(Thread.java:842)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- testMethod -->
  <testcase classname="testNGExamples.TestExample12" name="ncLogin2" time="0.011"/>
  <testcase classname="testNGExamples.TestExample12" name="ncLogin2" time="0.039"/>
  <testcase classname="testNGExamples.TestExample13" name="googleApp" time="0.013">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNGExamples.TestExample13.googleApp(TestExample13.java:25)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- googleApp -->
  <testcase classname="testNGExamples.TestExample13" name="faceBook" time="8.15"/>
  <testcase classname="testNGExamples.TestExample4" name="method1" time="0.002">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNGExamples.TestExample4.method1(TestExample4.java:10)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase classname="testNGExamples.TestExample5" name="method1" time="0.005">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNGExamples.TestExample5.method1(TestExample5.java:10)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase classname="testNGExamples.TestExample8" name="method1" time="0.007">
    <failure type="java.lang.AssertionError" message="Both are not same expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Both are not same expected [false] but found [true]
at testNGExamples.TestExample8.method1(TestExample8.java:14)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase classname="testNGExamples.TestExample9" name="method1" time="0.025">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Both are not same expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Both are not same expected [true] but found [false]
at testNGExamples.TestExample9.method1(TestExample9.java:22)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase classname="testNGExamples.TestExample2" name="testMethod1" time="0.002"/>
  <testcase classname="testNGExamples.TestExample2" name="testMethod2" time="0.006"/>
  <testcase classname="testNGExamples.TestExample3" name="ncLogin" time="18.744"/>
  <testcase classname="testNGExamples.TestExample1" name="method1" time="0.002"/>
  <testcase classname="testNGExamples.TestExample13" name="linkedIn" time="0.0">
    <skipped/>
  </testcase> <!-- linkedIn -->
  <testcase classname="testNGExamples.TestExample4" name="method2" time="0.0">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase classname="testNGExamples.TestExample4" name="method3" time="0.0">
    <skipped/>
  </testcase> <!-- method3 -->
  <testcase classname="testNGExamples.TestExample5" name="method2" time="0.0">
    <skipped/>
  </testcase> <!-- method2 -->
  <testcase classname="testNGExamples.TestExample5" name="method3" time="0.0">
    <skipped/>
  </testcase> <!-- method3 -->
  <testcase classname="testNGExamples.TestExample6" name="Dashboard" time="0.002"/>
  <testcase classname="testNGExamples.TestExample6" name="catalog" time="0.003"/>
  <testcase classname="testNGExamples.TestExample6" name="Login" time="0.0">
    <ignored/>
  </testcase> <!-- Login -->
</testsuite> <!-- NCTest -->
